/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2025-12-11T16:16:37.348Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "0bbc758b-af93-4bf8-a52a-0a82cd12d801",
    name: "Ingredients",
    slug: "ingredients",
    showInHeader: true,
    showInFooter: true
  },
  {
    id: "e7b08c70-7aa1-4eea-b9ae-f689350631dc",
    name: "Recalls",
    slug: "recalls",
    showInHeader: true,
    showInFooter: true
  },
  {
    id: "17d75358-05a4-49c3-87bc-64112878fe10",
    name: "Lawsuits",
    slug: "lawsuits",
    showInHeader: true,
    showInFooter: true
  }
]
