/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: WhatTheFood
 * Generated: 2025-12-11T16:16:37.348Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "b6371f6e-e94f-4a6d-a4ac-c7176a60e6b5",
    name: "WhatTheFood",
    description: "WhatTheFood empowers families to lead healthier lives by providing expert insights and trusted resources on reducing exposure to harmful chemicals in everyday products.",
    url: "https://whatthefood.life",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai",
    legalEmail: "support@banedigital.com",
    privacyEmail: "support@banedigital.com",
    tagline: "Empowering families with knowledge for a cleaner, safer lifestyle"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to WhatTheFood",
    subtitle: "Empowering families with knowledge for a cleaner, safer lifestyle"
  },

  // Default author information
  author: {
    name: "WhatTheFood Team",
    bio: "WhatTheFood empowers families to lead healthier lives by providing expert insights and trusted resources on reducing exposure to harmful chemicals ...",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Health & Wellness Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from WhatTheFood delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Ingredients",
      icon: "FileText",
      slug: "ingredients"
    },
    { 
      name: "Recalls",
      icon: "FileText",
      slug: "recalls"
    },
    { 
      name: "Lawsuits",
      icon: "FileText",
      slug: "lawsuits"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "35f098e5-e001-4d5b-a811-0b34f6d75eed",
      name: "Tom Reynolds",
      bio: "Tom brings a warm, conversational tone to his writing, drawing on his extensive experience as a consultant in sustainable living. He excels at crafting practical how-to guides and insightful product reviews, making the journey towards a healthier lifestyle approachable and enjoyable. His enthusiasm for eco-friendly solutions is infectious, encouraging readers to embrace change.",
      image: "/authors/35f098e5-e001-4d5b-a811-0b34f6d75eed.jpg",
      role: "Sustainable Living Consultant"
    },
    {
      id: "819eadcd-bd09-4e76-91ba-8d49e536e8c2",
      name: "Dr. Emily Foster",
      bio: "Dr. Foster combines her extensive expertise in toxicology with a passionate commitment to public health. Her writing is both authoritative and accessible, aiming to demystify complex scientific information. With a knack for storytelling, she empowers readers with the knowledge needed to make safer choices for their families.",
      image: "/authors/819eadcd-bd09-4e76-91ba-8d49e536e8c2.jpg",
      role: "Toxicologist & Health Advocate"
    },
    {
      id: "d93ae72a-030c-4ea1-92ec-e864fb4da60f",
      name: "Sarah Greenfield",
      bio: "Sarah is a meticulous investigator with a keen eye for uncovering hidden stories in the world of consumer products. Her writing is engaging and thought-provoking, often challenging readers to reconsider their everyday choices. With a strong sense of advocacy, she inspires change through compelling narratives and well-researched facts.",
      image: "/authors/d93ae72a-030c-4ea1-92ec-e864fb4da60f.jpg",
      role: "Investigative Journalist & Wellness Enthusiast"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
