/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: WhatTheFood
 * Generated: 2025-11-24T19:03:08.747Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    name: "WhatTheFood",
    description: "WhatTheFood empowers families to lead healthier lives by providing expert insights and trusted resources on reducing exposure to harmful chemicals in everyday products.",
    url: "https://whatthefood.life",
    logoPath: "/logo.jpg"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to WhatTheFood",
    subtitle: "CleanLiving Hub empowers families to lead healthier lives by providing trusted, expert insights and resources on minimizing exposure to harmful chemicals, ensuring peace of mind and a safer home environment."
  },

  // Default author information
  author: {
    name: "WhatTheFood Team",
    bio: "WhatTheFood empowers families to lead healthier lives by providing expert insights and trusted resources on reducing exposure to harmful chemicals ...",
    role: "Content Creator",
    image: "/placeholder-user.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Health & Wellness Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from WhatTheFood delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Ingredients",
      icon: "FileText",
      slug: "ingredients"
    },
    { 
      name: "Recalls",
      icon: "FileText",
      slug: "recalls"
    },
    { 
      name: "Lawsuits",
      icon: "FileText",
      slug: "lawsuits"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "oklch(0.38 0.19 221)",      // #2563EB
    secondary: "oklch(0.45 0.04 215)",  // #64748B
    accent: "oklch(0.65 0.23 38)"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "oklch(0.48 0.19 221)",
    secondary: "oklch(0.55 0.04 215)",
    accent: "oklch(0.70 0.23 38)"
  }
}
